# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SimulateHawkes <- function(a_lambda0, a_alpha, a_beta, horizon) {
    .Call('hawkes_SimulateHawkes', PACKAGE = 'hawkes', a_lambda0, a_alpha, a_beta, horizon)
}

