# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Attribute <- function(alea, t, I_star, m_lambda) {
    .Call('hawkes_Attribute', PACKAGE = 'hawkes', alea, t, I_star, m_lambda)
}

SimulateHawkes <- function(a_lambda0, a_alpha, a_beta, horizon) {
    .Call('hawkes_SimulateHawkes', PACKAGE = 'hawkes', a_lambda0, a_alpha, a_beta, horizon)
}

essai <- function(a) {
    .Call('hawkes_essai', PACKAGE = 'hawkes', a)
}

