// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SimulateHawkes
std::vector<std::vector<double> > SimulateHawkes(SEXP lambda0, SEXP alpha, SEXP beta, SEXP horizon);
RcppExport SEXP hawkes_SimulateHawkes(SEXP lambda0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type lambda0(lambda0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type horizon(horizonSEXP );
        std::vector<std::vector<double> > __result = SimulateHawkes(lambda0, alpha, beta, horizon);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
